POST https://smart-triagem-backend  .vercel.app/api/v1/screening
Content-Type: application/json

{
  "symptoms": ["Dor de cabeça", "Febre", "Dor no corpo", "Ânsea de Vomito"],
  "medications": ["omesH"],
  "patient": {
    "name": "Erivelton Lima",
    "email": "eriveltonlima@uol.com",
    "sex": "MALE",
    "phone": "999999999",
    "age": 43
  }
}

###

GET http://localhost:3001/api/v1/screening?phone=999999999